#### Conv-TasNet Setting
name: Conv_Tasnet
gpu_ids: [0]
#gpu_ids: [0]
epochs: 100

#### Dataset Configure
datasets:
  num_workers: 4
  batch_size: 5
  fs: 8000
  train:
    mix_scp: /mnt/Conv-TasNet/Conv_TasNet_Pytorch/data/audio_scp_8k/train_100/clean/tr_mix.scp
    tar_scp_spk1: /mnt/Conv-TasNet/Conv_TasNet_Pytorch/data/audio_scp_8k/train_100/tr_s1.scp
    tar_scp_spk2: /mnt/Conv-TasNet/Conv_TasNet_Pytorch/data/audio_scp_8k/train_100/tr_s2.scp
    txt_scp_spk1: /mnt/Conv-TasNet/Conv_TasNet_TSE/text/train_100/GT_train_100_spk1.csv
    txt_scp_spk2: /mnt/Conv-TasNet/Conv_TasNet_TSE/text/train_100/GT_train_100_spk2.csv
    sr: 8000
  val:
    mix_scp: /mnt/Conv-TasNet/Conv_TasNet_Pytorch/data/audio_scp_8k/dev/clean/cv_mix.scp
    tar_scp_spk1: /mnt/Conv-TasNet/Conv_TasNet_Pytorch/data/audio_scp_8k/dev/cv_s1.scp
    tar_scp_spk2: /mnt/Conv-TasNet/Conv_TasNet_Pytorch/data/audio_scp_8k/dev/cv_s2.scp
    txt_scp_spk1: /mnt/Conv-TasNet/Conv_TasNet_TSE/text/val/GT_val_spk1.csv
    txt_scp_spk2: /mnt/Conv-TasNet/Conv_TasNet_TSE/text/val/GT_val_spk2.csv
    sr: 8000


#### training settings: learning rate scheme, loss
train:
  optimizer: adam
  min_lr: !!float 1e-8
  patience: 2
  factor: 0.5
  logging_period: 200
  clip_norm: 200
  num_epochs: 100
  checkpoint: Conv-TasNet-mean_concat

optimizer_kwargs:
  lr: !!float 1e-3
  weight_decay: !!float 1e-5

#### network configure
net_conf:
  N: 512
  L: 16
  B: 128
  H: 512
  P: 3
  X: 8
  R: 3
  norm: gln
  activate: relu
  causal: false
  text_model_name: "bert-base-uncased"   # 文本模型名称
  pooling_method: "mean"                 # 池化方法
  # attn_dim: 256                         # 注意力维度
  ##skip_con: false

#### resume model
resume:
  path: /mnt/Conv-TasNet/Conv_TasNet_TSE
  resume_state: false